#!/usr/bin/env python3
"""Generate printable tag sheets for custom ArUco dictionaries.

Formats custom dictionary contact sheets matching the style of:
  - DICT_4X4_1000-grid15x20.png (compact white-background grid)
  - tag_sheet.png (physical-size sections with scale rulers)

Loads dictionaries from NPZ files generated by create_custom_4x4_dicts.py.

Usage:
    python nn-aruco-detection-test/generate_tag_sheets.py \
        --npz-a nn-aruco-detection-test/results/custom_dicts/custom_4x4_A100_d4_20260410_103938.npz \
        --npz-b nn-aruco-detection-test/results/custom_dicts/custom_4x4_B300_d3_20260410_103938.npz \
        --output-dir nn-aruco-detection-test/results/custom_dicts
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import cv2.aruco as aruco
import numpy as np


def load_custom_dictionary(npz_path: str | Path):
    """Load a custom ArUco dictionary from an NPZ file."""
    data = np.load(str(npz_path), allow_pickle=True)
    d = aruco.Dictionary()
    d.bytesList = data["bytesList"]
    d.markerSize = 4
    d.maxCorrectionBits = int(data["max_correction_bits"])
    n_markers = d.bytesList.shape[0]
    min_d = int(data["min_distance"])
    return d, n_markers, min_d


def generate_grid_sheet(
    dictionary: aruco.Dictionary,
    n_markers: int,
    name: str,
    min_d: int,
    output_path: Path,
    cols: int = 10,
    marker_px: int = 48,
    dpi: int = 300,
):
    """Generate a compact white-background grid sheet (like DICT_4X4_1000-grid15x20.png).

    Each marker is rendered with a white border, ID number below,
    on a clean white background.
    """
    rows = (n_markers + cols - 1) // cols

    # Layout parameters
    id_font = cv2.FONT_HERSHEY_SIMPLEX
    id_font_scale = 0.35
    id_font_thickness = 1
    id_height = 14  # space for ID text below marker
    gap_x = 12  # horizontal gap between markers
    gap_y = 6   # vertical gap between rows (above marker)
    margin_top = 40  # space for title
    margin_side = 20
    margin_bottom = 20

    cell_w = marker_px + gap_x
    cell_h = marker_px + id_height + gap_y

    sheet_w = cols * cell_w + margin_side * 2
    sheet_h = rows * cell_h + margin_top + margin_bottom

    # White background
    sheet = np.ones((sheet_h, sheet_w), dtype=np.uint8) * 255

    # Title
    title = f"{name}  ({n_markers} markers, min_d={min_d})"
    cv2.putText(sheet, title, (margin_side, margin_top - 12),
                id_font, 0.5, 0, 1, cv2.LINE_AA)

    for mid in range(n_markers):
        r, c = divmod(mid, cols)
        x = c * cell_w + margin_side
        y = r * cell_h + margin_top

        # Generate marker image (includes 1-cell white border from OpenCV)
        img = aruco.generateImageMarker(dictionary, mid, marker_px)

        # Place marker
        sheet[y:y + marker_px, x:x + marker_px] = img

        # ID label centered below marker
        label = str(mid)
        (tw, th), _ = cv2.getTextSize(label, id_font, id_font_scale, id_font_thickness)
        tx = x + (marker_px - tw) // 2
        ty = y + marker_px + id_height - 2
        cv2.putText(sheet, label, (tx, ty), id_font, id_font_scale, 0,
                    id_font_thickness, cv2.LINE_AA)

    cv2.imwrite(str(output_path), sheet)
    print(f"  Grid sheet saved: {output_path}  ({sheet_w}x{sheet_h} px)")


def draw_scale_ruler(sheet, x, y, length_mm, dpi, label="10 mm"):
    """Draw a physical scale ruler at the given position."""
    px_per_mm = dpi / 25.4
    ruler_length_px = int(length_mm * px_per_mm)
    tick_height = 8
    small_tick_height = 4

    font = cv2.FONT_HERSHEY_SIMPLEX

    # Main line
    cv2.line(sheet, (x, y), (x + ruler_length_px, y), 0, 1)

    # Ticks every mm
    for mm in range(length_mm + 1):
        tx = x + int(mm * px_per_mm)
        if mm % 5 == 0:
            cv2.line(sheet, (tx, y - tick_height), (tx, y + tick_height), 0, 1)
        else:
            cv2.line(sheet, (tx, y - small_tick_height), (tx, y + small_tick_height), 0, 1)

    # Label
    cv2.putText(sheet, label, (x + ruler_length_px + 8, y + 4),
                font, 0.35, 0, 1, cv2.LINE_AA)


def generate_print_sheet(
    dictionary: aruco.Dictionary,
    n_markers: int,
    name: str,
    min_d: int,
    output_path: Path,
    tag_sizes_mm: list[float] = [1.5, 2.0, 2.5],
    cols: int = 10,
    dpi: int = 300,
    ids_per_section: int | None = None,
):
    """Generate a printable tag sheet with physical size sections and scale rulers.

    Matches the style of tag_sheet.png with multiple size sections.
    """
    px_per_mm = dpi / 25.4

    if ids_per_section is None:
        ids_per_section = n_markers

    n_ids = min(ids_per_section, n_markers)
    rows_per_section = (n_ids + cols - 1) // cols

    # Layout parameters
    font = cv2.FONT_HERSHEY_SIMPLEX

    margin_top = 40
    margin_side = int(10 * px_per_mm)
    section_gap = int(8 * px_per_mm)
    id_space = int(2.5 * px_per_mm)  # space for ID text
    row_gap = int(1.5 * px_per_mm)
    ruler_space = int(6 * px_per_mm)  # space for ruler below section

    # Compute section height for each tag size
    sections = []
    for size_mm in tag_sizes_mm:
        marker_px = max(int(size_mm * px_per_mm), 6)  # marker size in pixels
        col_spacing = max(int(3.5 * px_per_mm), marker_px + int(1.5 * px_per_mm))
        row_height = marker_px + id_space + row_gap

        section_h = rows_per_section * row_height + ruler_space
        section_w = cols * col_spacing

        sections.append({
            "size_mm": size_mm,
            "marker_px": marker_px,
            "col_spacing": col_spacing,
            "row_height": row_height,
            "section_h": section_h,
            "section_w": section_w,
        })

    # Total sheet dimensions
    total_h = margin_top
    for i, sec in enumerate(sections):
        total_h += int(4 * px_per_mm)  # title space
        total_h += sec["section_h"]
        if i < len(sections) - 1:
            total_h += section_gap

    max_section_w = max(s["section_w"] for s in sections)
    total_w = max_section_w + margin_side * 2

    # White background
    sheet = np.ones((total_h, total_w), dtype=np.uint8) * 255

    # Main title
    main_title = f"{name}  (min_d={min_d}, {n_markers} markers)"
    cv2.putText(sheet, main_title, (margin_side, 25),
                font, 0.45, 0, 1, cv2.LINE_AA)

    cursor_y = margin_top

    for sec in sections:
        size_mm = sec["size_mm"]
        marker_px = sec["marker_px"]
        col_spacing = sec["col_spacing"]
        row_height = sec["row_height"]

        # Section title
        section_title = f"{size_mm} mm  (IDs 0-{n_ids - 1})"
        cv2.putText(sheet, section_title, (margin_side, cursor_y + int(2.5 * px_per_mm)),
                    font, 0.4, 0, 1, cv2.LINE_AA)
        cursor_y += int(4 * px_per_mm)

        # Draw markers
        for mid in range(n_ids):
            r, c = divmod(mid, cols)
            x = c * col_spacing + margin_side
            y = cursor_y + r * row_height

            # Generate and resize marker
            img = aruco.generateImageMarker(dictionary, mid, max(marker_px, 20))
            if img.shape[0] != marker_px:
                img = cv2.resize(img, (marker_px, marker_px), interpolation=cv2.INTER_NEAREST)

            # Place marker
            y_end = min(y + marker_px, sheet.shape[0])
            x_end = min(x + marker_px, sheet.shape[1])
            if y_end > y and x_end > x:
                sheet[y:y_end, x:x_end] = img[:y_end - y, :x_end - x]

            # ID label
            label = str(mid)
            font_scale = 0.28 if size_mm <= 1.5 else 0.32
            (tw, _), _ = cv2.getTextSize(label, font, font_scale, 1)
            tx = x
            ty = y + marker_px + int(1.8 * px_per_mm)
            if ty < sheet.shape[0]:
                cv2.putText(sheet, label, (tx, ty), font, font_scale, 0, 1, cv2.LINE_AA)

        # Scale ruler
        ruler_y = cursor_y + rows_per_section * row_height + int(1 * px_per_mm)
        if ruler_y + 20 < sheet.shape[0]:
            draw_scale_ruler(sheet, margin_side, ruler_y, 10, dpi, "10 mm")

        cursor_y += sec["section_h"] + section_gap

    cv2.imwrite(str(output_path), sheet)
    print(f"  Print sheet saved: {output_path}  ({total_w}x{total_h} px, {dpi} dpi)")


def main():
    p = argparse.ArgumentParser(description="Generate printable tag sheets")
    p.add_argument("--npz-a", required=True, help="NPZ file for dictionary A")
    p.add_argument("--npz-b", required=True, help="NPZ file for dictionary B")
    p.add_argument("--output-dir", default="nn-aruco-detection-test/results/custom_dicts")
    p.add_argument("--dpi", type=int, default=300)
    p.add_argument("--tag-sizes", type=float, nargs="+", default=[1.5, 2.0, 2.5],
                   help="Tag sizes in mm for print sheets")
    args = p.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load dictionaries
    print("Loading dictionaries...")
    dict_a, n_a, min_d_a = load_custom_dictionary(args.npz_a)
    dict_b, n_b, min_d_b = load_custom_dictionary(args.npz_b)
    print(f"  Dict A: {n_a} markers, min_d={min_d_a}")
    print(f"  Dict B: {n_b} markers, min_d={min_d_b}")

    name_a = f"custom_4x4_A{n_a}_d{min_d_a}"
    name_b = f"custom_4x4_B{n_b}_d{min_d_b}"

    # Generate grid-style contact sheets (like DICT_4X4_1000-grid15x20.png)
    print("\nGenerating grid contact sheets...")
    generate_grid_sheet(
        dict_a, n_a, name_a, min_d_a,
        output_dir / f"{name_a}_contact_sheet.png",
        cols=10, marker_px=48,
    )
    generate_grid_sheet(
        dict_b, n_b, name_b, min_d_b,
        output_dir / f"{name_b}_contact_sheet.png",
        cols=15, marker_px=36,
    )

    # Generate printable tag sheets (like tag_sheet.png)
    print("\nGenerating printable tag sheets...")
    generate_print_sheet(
        dict_a, n_a, name_a, min_d_a,
        output_dir / f"{name_a}_print_sheet.png",
        tag_sizes_mm=args.tag_sizes,
        cols=10, dpi=args.dpi,
    )
    generate_print_sheet(
        dict_b, n_b, name_b, min_d_b,
        output_dir / f"{name_b}_print_sheet.png",
        tag_sizes_mm=args.tag_sizes,
        cols=10, dpi=args.dpi,
        ids_per_section=50,  # split into manageable pages
    )

    print("\nDone.")


if __name__ == "__main__":
    main()
