# %%
# VS Code/Jupyter interactive script for sleep and interaction exploration.
try:
    get_ipython().run_line_magic("matplotlib", "qt")  # type: ignore[name-defined]
except Exception:
    pass

import importlib
import sys
from pathlib import Path

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print

repo_root = Path.cwd().resolve()
for candidate in [repo_root, *repo_root.parents]:
    if (candidate / "analysis" / "sleep_analysis_utils.py").exists():
        repo_root = candidate
        break
else:
    raise FileNotFoundError("Could not find analysis/sleep_analysis_utils.py from the current working directory")

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

import analysis.colony_speed_utils as cs
import analysis.interaction_analysis_utils as ia
import analysis.sleep_analysis_utils as sleep_utils
from analysis.figure_saving import install_auto_savefig

importlib.reload(cs)
importlib.reload(ia)
importlib.reload(sleep_utils)


# %%
# Edit these settings first. Defaults load one chunk/side for fast plotting.
DATASET_ROOT = Path("/home/sam-reiter/bucket/ReiterU/Ants/basler/20260702/block01")
INTERACTION_ROOT = DATASET_ROOT / "interactions"
TRACKS_ROOT = DATASET_ROOT / "tracks"
SPEED_ROOT = DATASET_ROOT / "stitched" / "speed_vectors"
SLEEP_PREDICTIONS_ROOT = DATASET_ROOT / "stitched" / "sleep_predictions"
FIGURE_ROOT = DATASET_ROOT / "analysis_outputs" / "sleep_analysis_figures"
SAVE_FIGURES = True
FIGURE_DPI = 180

SIDE = "left"  # "left" or "right"
CHUNKS = "all"  # Use "all" for the full side, or ["000", "001"].
MAX_CHUNKS = None
FPS = 24.0
MIN_PRESENT_FRAC = 0.40

SINGLE_ANT_ROW = None       # Row from speed_tracks; overrides track id when not None.
SINGLE_ANT_TRACK_ID = 22  # Set to an integer TrackID, or None for first selected track.
SINGLE_ANT_SIDE = 'left'

BIN_SECONDS = 30.0
SPEED_SMOOTH_SECONDS = 5 * 60
SPEED_YLIM = None
INTERACTION_YLIM = None
INTERACTION_BOUT_GAP_SECONDS = 2.0


# %%
# Resolve chunk files, load speed-vector metadata, and load directed interactions.
chunks = ia.resolve_chunks(
    INTERACTION_ROOT,
    TRACKS_ROOT,
    chunks=CHUNKS,
    side=SIDE,
    fps=FPS,
    max_chunks=MAX_CHUNKS,
)
chunk_summary = ia.describe_chunks(chunks)
ANALYSIS_FRAME_START = min(int(chunk.chunk_global_frame_offset) for chunk in chunks)
ANALYSIS_FRAME_STOP = max(int(chunk.chunk_global_frame_offset + chunk.chunk_frame_count) for chunk in chunks)

speed_tracks_all = cs.load_speed_tracks(SPEED_ROOT)
speed_tracks = cs.select_tracks(speed_tracks_all, MIN_PRESENT_FRAC)
speed_tracks_side = speed_tracks[speed_tracks["side"] == SINGLE_ANT_SIDE].reset_index(drop=False)
if speed_tracks_side.empty:
    raise ValueError(f"No speed tracks passed MIN_PRESENT_FRAC={MIN_PRESENT_FRAC} for side={SINGLE_ANT_SIDE!r}")

if SINGLE_ANT_TRACK_ID is None and SINGLE_ANT_ROW is None:
    SINGLE_ANT_TRACK_ID = int(speed_tracks_side.iloc[0]["track_id"])
single_ant_figure_label = (
    f"track{SINGLE_ANT_TRACK_ID}"
    if SINGLE_ANT_ROW is None
    else (
        f"row{SINGLE_ANT_ROW}"
        if SINGLE_ANT_TRACK_ID is None
        else f"row{SINGLE_ANT_ROW}_track{SINGLE_ANT_TRACK_ID}"
    )
)
install_auto_savefig(
    FIGURE_ROOT / f"{SINGLE_ANT_SIDE}_{single_ant_figure_label}",
    prefix=f"sleep_analysis_{SINGLE_ANT_SIDE}_{single_ant_figure_label}",
    dpi=FIGURE_DPI,
    enabled=SAVE_FIGURES,
)

interactions_raw = ia.load_interactions_for_chunks(chunks)
interaction_bout_counts_by_track = ia.interaction_bout_counts_by_track(
    interactions_raw,
    chunk_global_frame_offset=0,
    fps=FPS,
    event_gap_seconds=INTERACTION_BOUT_GAP_SECONDS,
)
interaction_counts_by_track = interaction_bout_counts_by_track  # Backward-compatible alias for interactive use.

chunk_table = pd.DataFrame(
    [
        {
            "chunk": chunk.chunk,
            "side": chunk.side,
            "start": ia.format_clock_time(chunk.chunk_start_clock_seconds),
            "frame_offset": chunk.chunk_global_frame_offset,
            "n_frames": chunk.chunk_frame_count,
            "interaction_file": chunk.interaction_path.name,
        }
        for chunk in chunks
    ]
)

print(f"Chunk selection: {chunk_summary} ({SIDE})")
print(f"Loaded speed tracks: {len(speed_tracks):,}/{len(speed_tracks_all):,} passing present_frac > {MIN_PRESENT_FRAC:g}")
print(f"Frame-level interaction rows loaded: {len(interactions_raw):,}")
print(
    "Interaction bouts counted: "
    f"{sum(int(counts['n_interactions_total'].sum()) for counts in interaction_bout_counts_by_track.values()):,} "
    f"(gap {INTERACTION_BOUT_GAP_SECONDS:g}s)"
)
print(f"Selected ant: row={SINGLE_ANT_ROW}, track_id={SINGLE_ANT_TRACK_ID}, side={SINGLE_ANT_SIDE}")
display(chunk_table)
display(
    speed_tracks_side[
        ["index", "side", "track_id", "track_name", "present_frac", "n_observed_frames", "n_frames"]
    ].head(20)
)


# %%
# Load classifier sleep predictions generated by analysis/compute_track_sleep_predictions.py.
sleep_tracks = sleep_utils.attach_sleep_predictions_to_tracks(
    speed_tracks,
    SLEEP_PREDICTIONS_ROOT,
    require_all=False,
)
sleep_tracks = sleep_tracks[sleep_tracks["has_sleep_predictions"]].reset_index(drop=True)
sleep_tracks_side = sleep_tracks[sleep_tracks["side"] == SINGLE_ANT_SIDE].reset_index(drop=True)
if sleep_tracks_side.empty:
    raise ValueError(f"No sleep predictions available for side={SINGLE_ANT_SIDE!r}")

print(f"Loaded sleep predictions for {len(sleep_tracks):,}/{len(speed_tracks):,} selected tracks")
display(
    sleep_tracks_side[
        [
            "side",
            "track_id",
            "track_name",
            "sleep_prediction_present_frac",
            "sleep_fraction_predicted_frames",
            "mean_sleep_probability",
        ]
    ].head(20)
)


# %%
# Single-ant plot: classifier sleep fraction, speed, and directed social interactions.
single_ant_sleep_interactions = sleep_utils.plot_single_ant_sleep_predictions_interactions(
    sleep_tracks,
    speed_tracks,
    interactions_raw,
    row_number=SINGLE_ANT_ROW,
    track_id=SINGLE_ANT_TRACK_ID,
    side=SINGLE_ANT_SIDE,
    bin_seconds=BIN_SECONDS,
    speed_smooth_seconds=SPEED_SMOOTH_SECONDS,
    analysis_frame_start=ANALYSIS_FRAME_START,
    analysis_frame_stop=ANALYSIS_FRAME_STOP,
    speed_ylim=SPEED_YLIM,
    interaction_ylim=INTERACTION_YLIM,
    counts_by_track=interaction_bout_counts_by_track,
)
display(single_ant_sleep_interactions.head(20))


# %%
# Bout-level quantification for the plotted ant, using predicted sleep bouts.
single_ant_sleep_bouts = single_ant_sleep_interactions.attrs.get("sleep_bouts", pd.DataFrame()).copy()
if single_ant_sleep_bouts.empty:
    single_ant_sleep_summary = pd.DataFrame()
else:
    single_ant_sleep_bouts["has_interaction"] = single_ant_sleep_bouts["n_interactions_total"] > 0
    single_ant_sleep_summary = pd.DataFrame(
        [
            {
                "state": "predicted_sleep",
                "n_bouts": len(single_ant_sleep_bouts),
                "total_bout_duration_s": float(single_ant_sleep_bouts["bout_duration_seconds"].sum()),
                "median_bout_duration_s": float(single_ant_sleep_bouts["bout_duration_seconds"].median()),
                "fraction_bouts_with_interaction": float(single_ant_sleep_bouts["has_interaction"].mean()),
                "mean_interaction_bouts_per_bout": float(single_ant_sleep_bouts["n_interactions_total"].mean()),
                "median_interaction_bouts_per_bout": float(single_ant_sleep_bouts["n_interactions_total"].median()),
                "mean_sleep_probability": float(single_ant_sleep_bouts["mean_sleep_probability"].mean()),
            }
        ]
    )
display(single_ant_sleep_bouts.head(20))
display(single_ant_sleep_summary)


# %%
# All predicted sleep bouts for the selected side, ready for downstream inspection.
predicted_sleep_bouts = sleep_utils.load_predicted_sleep_bouts(
    sleep_tracks_side,
    interaction_bout_counts_by_track,
    frame_start=ANALYSIS_FRAME_START,
    frame_stop=ANALYSIS_FRAME_STOP,
)
if predicted_sleep_bouts.empty:
    predicted_sleep_summary = pd.DataFrame()
else:
    predicted_sleep_bouts["has_interaction"] = predicted_sleep_bouts["n_interactions_total"] > 0
    predicted_sleep_summary = (
        predicted_sleep_bouts.groupby(["side"], as_index=False)
        .agg(
            n_tracks=("track_name", "nunique"),
            n_sleep_bouts=("bout_id", "size"),
            total_sleep_seconds=("bout_duration_seconds", "sum"),
            median_sleep_bout_seconds=("bout_duration_seconds", "median"),
            fraction_bouts_with_interaction=("has_interaction", "mean"),
            mean_sleep_probability=("mean_sleep_probability", "mean"),
        )
    )
display(predicted_sleep_summary)
display(predicted_sleep_bouts.head(30))


# %%
# Coarse correlations for the plotted ant.
same_ant_sleep_interaction_corr = single_ant_sleep_interactions[
    ["sleep_fraction", "speed_mm_s", "smoothed_speed_mm_s", "n_interactions_total"]
].corr(numeric_only=True)
display(same_ant_sleep_interaction_corr)

# %%
