#!/usr/bin/env python3
"""Estimate camera-grid homographies from a known ArUco/AprilTag board.

This script is a marker-ID based alternative to feature matching.  It detects
tags in each camXX image/video frame, maps each tag ID to its known board
position, and estimates one homography per camera into a shared board plane.

Default geometry matches the sequential board generated by
camera_cal/generate_aruco_grid/GenerateArucoGrid.py:

    cols=46, rows=35, tag_size=8, pitch=40, start_id=0

The output H matrices map camera image pixels to board coordinates.  For the
default board, those board coordinates are the generated pattern pixels
(1840 x 1400).  Use --layout-csv for randomized ID layouts.
"""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import cv2
import cv2.aruco as aruco
import numpy as np


IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}
VIDEO_SUFFIXES = {".avi", ".mp4", ".mov", ".mkv", ".mpeg", ".mpg", ".m4v"}
CAM_RE = re.compile(r"cam(\d{2})", re.IGNORECASE)


@dataclass(frozen=True)
class BoardMarker:
    marker_id: int
    top_left_x: float
    top_left_y: float


@dataclass(frozen=True)
class CameraResult:
    camera_index: int
    camera_number: int | None
    file: Path
    markers_detected: int
    valid_grid_markers: int
    rejected_candidates: int
    corner_points: int
    ransac_inlier_corners: int
    inlier_fraction: float
    board_rmse: float
    H: np.ndarray


def _cam_num(path: Path) -> int | None:
    match = CAM_RE.search(path.name)
    return int(match.group(1)) if match else None


def _cam_sort_key(path: Path) -> tuple[int, str]:
    cam_num = _cam_num(path)
    return (cam_num if cam_num is not None else 10**9, path.name.lower())


def _choose_one_file_per_camera(files: Iterable[Path]) -> list[Path]:
    grouped: dict[int, list[Path]] = {}
    no_cam: list[Path] = []
    for file in files:
        cam_num = _cam_num(file)
        if cam_num is None:
            no_cam.append(file)
        else:
            grouped.setdefault(cam_num, []).append(file)

    if not grouped:
        return sorted(files)

    chosen: list[Path] = []
    for cam_num in sorted(grouped):
        matches = sorted(grouped[cam_num], key=lambda p: p.name.lower())
        if len(matches) > 1:
            print(f"cam{cam_num:02d}: found {len(matches)} inputs; using {matches[0].name}")
        chosen.append(matches[0])

    if no_cam:
        print(f"Ignoring {len(no_cam)} files without camXX in the name.")
    return chosen


def collect_inputs(input_dir: Path, source: str) -> list[Path]:
    if not input_dir.is_dir():
        raise NotADirectoryError(input_dir)

    all_files = [p for p in input_dir.iterdir() if p.is_file() and not p.name.startswith(".")]
    if source == "auto":
        image_files = [p for p in all_files if p.suffix.lower() in IMAGE_SUFFIXES]
        video_files = [p for p in all_files if p.suffix.lower() in VIDEO_SUFFIXES]
        files = image_files if image_files else video_files
    elif source == "images":
        files = [p for p in all_files if p.suffix.lower() in IMAGE_SUFFIXES]
    else:
        files = [p for p in all_files if p.suffix.lower() in VIDEO_SUFFIXES]

    files = _choose_one_file_per_camera(files)
    files.sort(key=_cam_sort_key)
    if not files:
        raise RuntimeError(f"No {source} inputs found in {input_dir}")
    return files


def read_grayscale_input(path: Path, frame_index: int) -> np.ndarray:
    if path.suffix.lower() in IMAGE_SUFFIXES:
        image = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
        if image is None:
            raise IOError(f"Could not read image: {path}")
        return image

    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise IOError(f"Could not open video: {path}")

    if frame_index >= 0:
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)

    ok, frame = cap.read()
    cap.release()
    if not ok or frame is None:
        raise IOError(f"Could not read frame {frame_index} from video: {path}")
    if frame.ndim == 3:
        return cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    return frame


def dictionary_from_name(name: str) -> aruco.Dictionary:
    attr = name if name.startswith("DICT_") else f"DICT_{name}"
    if not hasattr(aruco, attr):
        known = sorted(k for k in dir(aruco) if k.startswith("DICT_"))
        raise SystemExit(
            f"Unknown ArUco dictionary {name!r}. "
            f"Known examples: {', '.join(known[:10])}, ..."
        )
    return aruco.getPredefinedDictionary(getattr(aruco, attr))


def load_custom_dictionary(path: Path) -> aruco.Dictionary:
    data = np.load(str(path), allow_pickle=True)
    required = {"bytesList", "max_correction_bits"}
    missing = required.difference(data.files)
    if missing:
        raise SystemExit(f"Custom dictionary {path} is missing keys: {sorted(missing)}")

    dictionary = aruco.Dictionary()
    dictionary.bytesList = data["bytesList"]
    dictionary.markerSize = int(data["marker_size"]) if "marker_size" in data.files else 4
    dictionary.maxCorrectionBits = int(data["max_correction_bits"])
    return dictionary


def set_if_attr(obj: object, name: str, value: object) -> None:
    if hasattr(obj, name):
        setattr(obj, name, value)


def odd_window(value: int) -> int:
    value = max(3, int(value))
    return value + 1 if value % 2 == 0 else value


def build_detector(args: argparse.Namespace) -> aruco.ArucoDetector:
    dictionary = (
        load_custom_dictionary(args.custom_dict)
        if args.custom_dict is not None
        else dictionary_from_name(args.dict)
    )
    params = aruco.DetectorParameters()
    set_if_attr(params, "adaptiveThreshConstant", float(args.adaptive_thresh_constant))
    set_if_attr(params, "adaptiveThreshWinSizeMin", odd_window(args.adaptive_thresh_win_min))
    set_if_attr(params, "adaptiveThreshWinSizeMax", odd_window(args.adaptive_thresh_win_max))
    set_if_attr(params, "adaptiveThreshWinSizeStep", max(1, int(args.adaptive_thresh_win_step)))
    set_if_attr(params, "errorCorrectionRate", float(args.error_correction_rate))
    set_if_attr(params, "minMarkerPerimeterRate", float(args.min_marker_perimeter_rate))
    set_if_attr(params, "maxMarkerPerimeterRate", float(args.max_marker_perimeter_rate))
    set_if_attr(params, "polygonalApproxAccuracyRate", float(args.polygonal_approx_accuracy_rate))
    if args.corner_refine != "none":
        refine_map = {
            "subpix": getattr(aruco, "CORNER_REFINE_SUBPIX", 1),
            "contour": getattr(aruco, "CORNER_REFINE_CONTOUR", 2),
            "april": getattr(aruco, "CORNER_REFINE_APRILTAG", 3),
        }
        set_if_attr(params, "cornerRefinementMethod", int(refine_map[args.corner_refine]))
    return aruco.ArucoDetector(dictionary, params)


def sequential_layout(args: argparse.Namespace) -> dict[int, BoardMarker]:
    markers: dict[int, BoardMarker] = {}
    for row in range(args.rows):
        for col in range(args.cols):
            marker_id = args.start_id + row * args.cols + col
            markers[marker_id] = BoardMarker(
                marker_id=marker_id,
                top_left_x=args.origin_x + col * args.pitch,
                top_left_y=args.origin_y + row * args.pitch,
            )
    return markers


def csv_layout(path: Path, args: argparse.Namespace) -> dict[int, BoardMarker]:
    """Load a randomized layout.

    Supported CSV schemas:
      id,row,col
      id,x,y

    The row/col schema uses --pitch and --origin-* to compute top-left
    coordinates.  The x/y schema treats x/y as top-left board coordinates.
    """
    markers: dict[int, BoardMarker] = {}
    with path.open(newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise SystemExit(f"Layout CSV has no header: {path}")
        fields = {name.strip().lower() for name in reader.fieldnames}
        has_row_col = {"id", "row", "col"}.issubset(fields)
        has_xy = {"id", "x", "y"}.issubset(fields)
        if not has_row_col and not has_xy:
            raise SystemExit(
                f"Layout CSV must contain either id,row,col or id,x,y columns: {path}"
            )

        for row in reader:
            marker_id = int(row["id"])
            if has_xy:
                x = float(row["x"])
                y = float(row["y"])
            else:
                x = args.origin_x + float(row["col"]) * args.pitch
                y = args.origin_y + float(row["row"]) * args.pitch
            markers[marker_id] = BoardMarker(marker_id=marker_id, top_left_x=x, top_left_y=y)
    if not markers:
        raise SystemExit(f"Layout CSV contains no markers: {path}")
    return markers


def build_board_layout(args: argparse.Namespace) -> dict[int, BoardMarker]:
    if args.layout_csv is not None:
        return csv_layout(args.layout_csv, args)
    return sequential_layout(args)


def marker_board_corners(marker: BoardMarker, marker_size: float) -> np.ndarray:
    x0 = marker.top_left_x
    y0 = marker.top_left_y
    return np.array(
        [
            [x0, y0],
            [x0 + marker_size, y0],
            [x0 + marker_size, y0 + marker_size],
            [x0, y0 + marker_size],
        ],
        dtype=np.float32,
    )


def estimate_camera_homography(
    file: Path,
    camera_index: int,
    image: np.ndarray,
    detector: aruco.ArucoDetector,
    board: dict[int, BoardMarker],
    marker_size: float,
    ransac_threshold: float,
    refine_inliers: bool,
) -> CameraResult:
    corners, ids, rejected = detector.detectMarkers(image)
    detected_count = 0 if ids is None else int(len(ids))
    rejected_count = int(len(rejected)) if rejected is not None else 0
    if ids is None or detected_count == 0:
        raise RuntimeError(f"{file.name}: no markers detected")

    src_chunks: list[np.ndarray] = []
    dst_chunks: list[np.ndarray] = []
    valid_markers = 0
    for marker_corners, marker_id in zip(corners, ids.reshape(-1)):
        marker = board.get(int(marker_id))
        if marker is None:
            continue
        src_chunks.append(np.asarray(marker_corners, dtype=np.float32).reshape(4, 2))
        dst_chunks.append(marker_board_corners(marker, marker_size))
        valid_markers += 1

    if valid_markers < 4:
        raise RuntimeError(
            f"{file.name}: {valid_markers} valid board markers; need at least 4"
        )

    src = np.vstack(src_chunks).astype(np.float32)
    dst = np.vstack(dst_chunks).astype(np.float32)
    H, inlier_mask = cv2.findHomography(src, dst, cv2.RANSAC, ransac_threshold)
    if H is None or inlier_mask is None:
        raise RuntimeError(f"{file.name}: homography estimation failed")

    inliers = inlier_mask.reshape(-1).astype(bool)
    if int(inliers.sum()) < 4:
        raise RuntimeError(f"{file.name}: homography has fewer than 4 inlier corners")

    if refine_inliers:
        H_refined, _ = cv2.findHomography(src[inliers], dst[inliers], 0)
        if H_refined is not None:
            H = H_refined

    projected = cv2.perspectiveTransform(src.reshape(-1, 1, 2), H).reshape(-1, 2)
    error = np.linalg.norm(projected[inliers] - dst[inliers], axis=1)
    rmse = float(np.sqrt(np.mean(error**2))) if error.size else float("nan")

    return CameraResult(
        camera_index=camera_index,
        camera_number=_cam_num(file),
        file=file,
        markers_detected=detected_count,
        valid_grid_markers=valid_markers,
        rejected_candidates=rejected_count,
        corner_points=int(len(src)),
        ransac_inlier_corners=int(inliers.sum()),
        inlier_fraction=float(inliers.mean()),
        board_rmse=rmse,
        H=np.asarray(H, dtype=np.float64),
    )


def board_canvas_size(args: argparse.Namespace, board: dict[int, BoardMarker]) -> tuple[int, int]:
    if args.canvas_width is not None and args.canvas_height is not None:
        return int(args.canvas_width), int(args.canvas_height)

    if args.layout_csv is None:
        width = args.origin_x + args.cols * args.pitch
        height = args.origin_y + args.rows * args.pitch
    else:
        max_x = max(m.top_left_x for m in board.values()) + args.marker_size
        max_y = max(m.top_left_y for m in board.values()) + args.marker_size
        width = max_x + args.trailing_margin
        height = max_y + args.trailing_margin
    return int(np.ceil(width)), int(np.ceil(height))


def write_stats_csv(path: Path, results: list[CameraResult]) -> None:
    fieldnames = [
        "camera_index",
        "camera_number",
        "file",
        "markers_detected",
        "valid_grid_markers",
        "rejected_candidates",
        "corner_points",
        "ransac_inlier_corners",
        "inlier_fraction",
        "board_rmse",
    ]
    with path.open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for result in results:
            writer.writerow(
                {
                    "camera_index": result.camera_index,
                    "camera_number": "" if result.camera_number is None else result.camera_number,
                    "file": result.file.name,
                    "markers_detected": result.markers_detected,
                    "valid_grid_markers": result.valid_grid_markers,
                    "rejected_candidates": result.rejected_candidates,
                    "corner_points": result.corner_points,
                    "ransac_inlier_corners": result.ransac_inlier_corners,
                    "inlier_fraction": f"{result.inlier_fraction:.9g}",
                    "board_rmse": f"{result.board_rmse:.9g}",
                }
            )


def warp_and_blend_to_board(
    files: list[Path],
    Hs: np.ndarray,
    canvas_size: tuple[int, int],
    frame_index: int,
) -> np.ndarray:
    width, height = canvas_size
    acc = np.zeros((height, width), dtype=np.float64)
    weight = np.zeros((height, width), dtype=np.float64)

    for file, H in zip(files, Hs):
        image = read_grayscale_input(file, frame_index=frame_index)
        warped = cv2.warpPerspective(
            image.astype(np.float32),
            H,
            (width, height),
            flags=cv2.INTER_LINEAR,
        )
        mask = cv2.warpPerspective(
            np.ones(image.shape, dtype=np.uint8),
            H,
            (width, height),
            flags=cv2.INTER_NEAREST,
        ) > 0
        acc[mask] += warped[mask]
        weight[mask] += 1.0

    blended = np.divide(acc, np.maximum(weight, 1.0))
    return np.clip(blended, 0, 255).astype(np.uint8)


def save_detection_debug(
    debug_dir: Path,
    file: Path,
    image: np.ndarray,
    detector: aruco.ArucoDetector,
) -> None:
    corners, ids, _ = detector.detectMarkers(image)
    canvas = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
    if ids is not None and len(ids) > 0:
        aruco.drawDetectedMarkers(canvas, corners, ids)
    out_path = debug_dir / f"{file.stem}_detections.png"
    cv2.imwrite(str(out_path), canvas)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Detect ArUco/AprilTag markers and estimate one image-to-board "
            "homography per camera."
        )
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Folder containing camXX still images or videos.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output folder. Default: <input>/aruco_board_calibration.",
    )
    parser.add_argument(
        "--source",
        choices=["auto", "images", "videos"],
        default="auto",
        help="Input type. Auto prefers images if present, otherwise videos.",
    )
    parser.add_argument(
        "--frame-index",
        type=int,
        default=0,
        help="Video frame index to read. Use 0 for first frame. Default: 0.",
    )
    parser.add_argument(
        "--expected-cameras",
        type=int,
        default=25,
        help="Expected number of camXX inputs. Set 0 to disable this check.",
    )
    parser.add_argument("--dict", default="DICT_APRILTAG_36h10")
    parser.add_argument("--custom-dict", type=Path, default=None)
    parser.add_argument("--rows", type=int, default=35)
    parser.add_argument("--cols", type=int, default=46)
    parser.add_argument("--start-id", type=int, default=0)
    parser.add_argument(
        "--layout-csv",
        type=Path,
        default=None,
        help="Optional randomized layout CSV with id,row,col or id,x,y columns.",
    )
    parser.add_argument(
        "--marker-size",
        type=float,
        default=8.0,
        help="Marker side length in board coordinate units. Default: 8.",
    )
    parser.add_argument(
        "--pitch",
        type=float,
        default=40.0,
        help="Distance between adjacent marker top-left corners. Default: 40.",
    )
    parser.add_argument("--origin-x", type=float, default=0.0)
    parser.add_argument("--origin-y", type=float, default=0.0)
    parser.add_argument("--trailing-margin", type=float, default=0.0)
    parser.add_argument("--canvas-width", type=int, default=None)
    parser.add_argument("--canvas-height", type=int, default=None)
    parser.add_argument("--ransac-threshold", type=float, default=2.5)
    parser.add_argument(
        "--no-refine-inliers",
        action="store_true",
        help="Do not re-fit the homography using RANSAC inlier corners.",
    )
    parser.add_argument("--adaptive-thresh-constant", type=float, default=3.0)
    parser.add_argument("--adaptive-thresh-win-min", type=int, default=10)
    parser.add_argument("--adaptive-thresh-win-max", type=int, default=40)
    parser.add_argument("--adaptive-thresh-win-step", type=int, default=10)
    parser.add_argument("--error-correction-rate", type=float, default=1.0)
    parser.add_argument("--min-marker-perimeter-rate", type=float, default=0.03)
    parser.add_argument("--max-marker-perimeter-rate", type=float, default=4.0)
    parser.add_argument("--polygonal-approx-accuracy-rate", type=float, default=0.03)
    parser.add_argument(
        "--corner-refine",
        choices=["none", "subpix", "contour", "april"],
        default="contour",
    )
    parser.add_argument("--hmats-name", default="aruco_board_H_mats.npz")
    parser.add_argument("--stats-name", default="aruco_board_homography_stats.csv")
    parser.add_argument("--map-name", default="aruco_board_global_map.png")
    parser.add_argument(
        "--no-map",
        action="store_true",
        help="Skip writing the blended board-coordinate global map.",
    )
    parser.add_argument(
        "--write-debug",
        action="store_true",
        help="Write per-camera detection overlay PNGs.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    files = collect_inputs(args.input, args.source)
    if args.expected_cameras and len(files) != args.expected_cameras:
        raise SystemExit(
            f"Expected {args.expected_cameras} inputs, found {len(files)} in {args.input}. "
            "Use --expected-cameras 0 to disable this check."
        )

    output_dir = args.output_dir or (args.input / "aruco_board_calibration")
    output_dir.mkdir(parents=True, exist_ok=True)

    detector = build_detector(args)
    board = build_board_layout(args)
    canvas_size = board_canvas_size(args, board)

    results: list[CameraResult] = []
    debug_dir = output_dir / "debug"
    if args.write_debug:
        debug_dir.mkdir(exist_ok=True)

    print(f"Loaded {len(files)} inputs from {args.input}")
    print(f"Board markers in layout: {len(board)}")
    print(f"Board canvas: {canvas_size[0]} x {canvas_size[1]}")

    for index, file in enumerate(files):
        image = read_grayscale_input(file, frame_index=args.frame_index)
        result = estimate_camera_homography(
            file=file,
            camera_index=index,
            image=image,
            detector=detector,
            board=board,
            marker_size=args.marker_size,
            ransac_threshold=args.ransac_threshold,
            refine_inliers=not args.no_refine_inliers,
        )
        results.append(result)
        print(
            f"{file.name}: markers={result.markers_detected} "
            f"valid={result.valid_grid_markers} "
            f"inliers={result.ransac_inlier_corners}/{result.corner_points} "
            f"rmse={result.board_rmse:.3f}"
        )
        if args.write_debug:
            save_detection_debug(debug_dir, file, image, detector)

    Hs = np.stack([result.H for result in results]).astype(np.float64)
    hmats_path = output_dir / args.hmats_name
    np.savez_compressed(
        hmats_path,
        H=Hs,
        files=np.array([result.file.name for result in results]),
        camera_numbers=np.array(
            [-1 if result.camera_number is None else result.camera_number for result in results],
            dtype=np.int32,
        ),
        board_canvas=np.array(canvas_size, dtype=np.float64),
        marker_size=np.array([args.marker_size], dtype=np.float64),
        pitch=np.array([args.pitch], dtype=np.float64),
        origin=np.array([args.origin_x, args.origin_y], dtype=np.float64),
        dictionary=np.array([args.dict]),
    )
    stats_path = output_dir / args.stats_name
    write_stats_csv(stats_path, results)

    print(f"Saved H matrices: {hmats_path}")
    print(f"Saved stats: {stats_path}")

    if not args.no_map:
        map_image = warp_and_blend_to_board(
            files=files,
            Hs=Hs,
            canvas_size=canvas_size,
            frame_index=args.frame_index,
        )
        map_path = output_dir / args.map_name
        ok = cv2.imwrite(str(map_path), map_image)
        if not ok:
            raise IOError(f"Failed to write global map: {map_path}")
        print(f"Saved global map: {map_path}")


if __name__ == "__main__":
    main()
